version:  '3'

services:

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-11-february-2020/group-projects/sagittarius/backend:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/run.sh'

  frontend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-11-february-2020/group-projects/sagittarius/frontend:latest
    restart: always
    command: 'sh /scripts/run_frontend_cmds.sh'
    volumes:
      - frontend:/frontend/build
      - media-files:/media-files
      - static-files:/static-files


volumes:
  media-files:
  static-files:
  postgres:
  frontend:
